version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      args:
        GITHUB_REPO: https://github.com/CK-codemax/strix-tech.git  # Pulls from your shell environment
    networks:
      - app-net

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

